timetracker/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Diagnostics;
using Timetracker.Models;

namespace Timetracker.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public ActionResult AddWorkTime(int timeInMinutes)
        {

            var connectionString = "workstation id=timetracker.mssql.somee.com;packet size=4096;user id=D4rQ_SQLLogin_1;pwd=9izweotsjl;data source=timetracker.mssql.somee.com;persist security info=False;initial catalog=timetracker;TrustServerCertificate=True";

            using (var connection = new SqlConnection(connectionString))
            {
                connection.Open();
                var currentTime = new SqlCommand("Select WorkTime FROM AspNetUsers Where UserName = \'" + User.Identity!.Name!.ToString() + "\'", connection).ExecuteScalar().ToString();
                timeInMinutes += int.Parse(currentTime!);
                var command = new SqlCommand("UPDATE AspNetUsers SET WorkTime = " + timeInMinutes + "Where UserName = \'" + User.Identity.Name + "\'", connection);
                command.ExecuteNonQuery();
                connection.Close();
            }
            return Json(new { success = true });
        }

        public ActionResult AddRestTime(int timeInMinutes)
        {

            var connectionString = "workstation id=timetracker.mssql.somee.com;packet size=4096;user id=D4rQ_SQLLogin_1;pwd=9izweotsjl;data source=timetracker.mssql.somee.com;persist security info=False;initial catalog=timetracker;TrustServerCertificate=True";

            using (var connection = new SqlConnection(connectionString))
            {
                connection.Open();
                var currentTime = new SqlCommand("Select RestTime FROM AspNetUsers Where UserName = \'" + User.Identity!.Name!.ToString() + "\'", connection).ExecuteScalar().ToString();
                timeInMinutes += int.Parse(currentTime!);
                var command = new SqlCommand("UPDATE AspNetUsers SET RestTime = " + timeInMinutes + "Where UserName = \'" + User.Identity.Name + "\'", connection);
                command.ExecuteNonQuery();
                connection.Close();
            }
            return Json(new { success = true });
        }

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

timetracker/Controllers/TaskTableController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace Timetracker.Controllers
{
    [Authorize]
    public class TaskTableController : Controller
    {
        public ActionResult AddTask(string? taskName, int taskPriority, string? deadline)
        {
            var connectionString = "workstation id=timetracker.mssql.somee.com;packet size=4096;user id=D4rQ_SQLLogin_1;pwd=9izweotsjl;data source=timetracker.mssql.somee.com;persist security info=False;initial catalog=timetracker;TrustServerCertificate=True";
            bool cond = true;
            using (var connection = new SqlConnection(connectionString))
            {
                connection.Open();
                var condition = new SqlCommand($"SELECT CASE WHEN EXISTS (SELECT * FROM AspNetTasks WHERE UserName = '{User.Identity!.Name}' AND TaskName = N'{taskName}' AND TaskPriority = {taskPriority} AND Deadline = '{deadline}') THEN 1 ELSE 0 END", connection).ExecuteScalar().ToString();
                cond = condition == "1";
                connection.Close();
                if (cond)
                {
                    return Json(new { success = cond });
                }
                connection.Open();
                var command = new SqlCommand($"INSERT INTO AspNetTasks VALUES ('{User.Identity!.Name}', N'{taskName}', {taskPriority}, '{deadline}')", connection);
                command.ExecuteNonQuery();
                connection.Close();
            }
            return Json(new { success = cond });
        }

        public ActionResult CompleteTask(string? taskName, int taskPriority, string? deadline)
        {
            var connectionString = "workstation id=timetracker.mssql.somee.com;packet size=4096;user id=D4rQ_SQLLogin_1;pwd=9izweotsjl;data source=timetracker.mssql.somee.com;persist security info=False;initial catalog=timetracker;TrustServerCertificate=True";
            bool cond = true;
            using (var connection = new SqlConnection(connectionString))
            {
                connection.Open();
                new SqlCommand($"DELETE FROM AspNetTasks WHERE UserName = '{User.Identity!.Name}' AND TaskName = N'{taskName}' AND TaskPriority = {taskPriority} AND Deadline = '{deadline}'", connection).ExecuteNonQuery();
                var currentTasks = int.Parse(new SqlCommand("Select CompletedTasks FROM AspNetUsers Where UserName = \'" + User.Identity!.Name!.ToString() + "\'", connection).ExecuteScalar().ToString()!);
                currentTasks++;
                var command = new SqlCommand("UPDATE AspNetUsers SET CompletedTasks = " + currentTasks + "Where UserName = \'" + User.Identity.Name + "\'", connection);
                command.ExecuteNonQuery();
                connection.Close();
            }
            return Json(new { success = cond });
        }

        public IActionResult TaskTable()
        {
            return View();
        }
    }
}

timetracker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = null;
}



<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&family=Lilita+One&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/css/main_page.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu</title>
</head>
<body>
    <div class="header">
        <div class="container">


            <div class="header-line">


                <div class="nav">
                    <a class="header_text" asp-action="Profile" asp-controller="Profile">@User.Identity!.Name</a>
                    <a class="user_pic" asp-action="Profile" asp-controller="Profile"><img src="~/images/Graphic_Files/user_pic.png" alt=""></a>
                    <!-- <btn><a href="#">Зарегистрироваться</a></btn> -->
                </div>


            </div>

        </div>
    </div>

    <div class="task_add" onclick="openPopup()">
        <a class="task_text" href="#">Добавление задачи</a>
        <a class="task_pic" href="#"><img src="~/images/Graphic_Files/plus.png" alt=""></a>
    </div>


    <div class="slidebar">
        <ul>

            <li class="logo">
                <a href="#">
                    <span class="icon"><div class="logo"><img src="~/images/Graphic_Files/timer.png" alt=""></div></span>
                    <div class="logo_text">Timetracker</div>
                </a>
            </li>
            <li>
                <a asp-action="Index" asp-route-returnurl="@ViewData[" ReturnUrl"]">
                    <span class="icon"><img src="~/images/Graphic_Files/menu_icon.png" alt=""></span>
                    <span class="text">Главная Страница</span>
                </a>
            </li>
            <li>
                <a asp-controller="TaskTable" asp-action="TaskTable" asp-route-returnurl="@ViewData[" ReturnUrl"]">
                    <span class="icon"><img src="~/images/Graphic_Files/task.png" alt=""></span>
                    <span class="text">Список задач</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="icon"><img src="~/images/Graphic_Files/calendar.png" alt=""></span>
                    <span class="text">События</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="icon"><img src="~/images/Graphic_Files/medal.png" alt=""></span>
                    <span class="text">Награды</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="icon"><img src="~/images/Graphic_Files/backpack.png" alt=""></span>
                    <span class="text">Инвентарь</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="icon"><img src="~/images/Graphic_Files/settings.png" alt=""></span>
                    <span class="text">Настройки</span>
                </a>
            </li>
            <div class="bottom">
            <li>
                <a asp-action="Logout" asp-controller="Account">
                    <span class="icon" ><img src="~/images/Graphic_Files/exit.png"></span>
                    <span class="text">Выйти</span>
                </a>
            </li>
    </div>

    </ul>
    </div>


    <section>
        <div class="timer_container">
            <!-- <h1>Начните работать уже сейчас</h1> -->
            <div class="painel">
                <p id="work">работа</p>
                <p id="break">отдых</p>
            </div>


            <div class="timer">
                <div class="circle">
                    <div class="time">
                        <p id="minutes"></p>
                        <p>:</p>
                        <p id="seconds"></p>
                    </div>
                </div>
            </div>
            <div class="controls">
                <button id="start" onclick="start()"><img src="~/images/Graphic_Files/play.png" alt=""></button>
                <button id="reset" onclick="reset()"><img src="~/images/Graphic_Files/reset.png" alt=""></button>
            </div>

        </div>
    </section>
    <div class="container_input">
        <div class="input-group">
            <label for="work-time">Время работы:</label>
            <input type="text" id="work-time" name="work-time" placeholder="00">
        </div>
        <div class="input-group">
            <label for="rest-time">Время отдыха:</label>
            <input type="text" id="rest-time" name="rest-time" placeholder="00">
        </div>
    </div>

    <div class="popup-content" id="popup">
        <span class="close" onclick="closePopup()">&times;</span>
        <h1>Новая задача</h1>
        <div class="inputbox">
            <label for="time">Название</label>
            <input type="text" id='task-name' placeholder="до 20 символов">
        </div>

        <div class="inputbox">
            <label for="importance">Значимость</label>
            <input type="text" id='task-importance'>
        </div>
        <div class="inputbox">
            <label for="deadline">Дедлайн</label>
            <input type="text" id="task-deadline">
        </div>

        <button onclick="addTask()">Добавить Задачу</button>
    </div>

    <div class="popup-content" id="popup">
        <span class="close" onclick="closePopup()">&times;</span>
        <h1>Новая задача</h1>
        <div class="inputbox">
            <label for="time">Название</label>
            <input type="text" id='task-name' placeholder="до 20 символов">
        </div>

        <div class="inputbox">
            <label for="importance">Значимость</label>
            <input type="text" id='task-importance'>
        </div>
        <div class="inputbox">
            <label for="deadline">Дедлайн</label>
            <input type="text" id="task-deadline">
        </div>

        <button onclick="addTask()">Добавить Задачу</button>
    </div>

    <script src="~/js/main page script.js"></script>

</body>
</html>